name: 'Güldest CI/CD'

on:
  push:
    branches: [ master ]

jobs:
  process:
    runs-on: ubuntu-latest 
    steps:
    - name: Kodu kopyala
      uses: actions/checkout@v4

    - name: Node kurulum
      uses: actions/setup-node@v4
      with: 
        node-version: '22.19.0'

    - name: Paket kurulum
      run: npm install

    - name: Proje derleme
      run: npx gulp build

    - name: Php test
      run: npx gulp phpTest

    - name: Sunucuya gönder
      uses: SaMKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: ./dist/